name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  delpoy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [unbuntu-latest, windows latest, macos-latest]
      
    name: Checkout Repository 
    steps:
      - name: Checkout-Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: action/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: |
          npm install

      - name: Build Project
        run: |
          npm run build # The build command of your project
        shell: bash

      - name: Push
        uses: s0/git-delpoy-subdir-action@develop
        env:
          REPO: my-deviste
          BRANCH: main # The branch name where you want to push the assets
          FOLDER: desktop # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
     
