name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 217.196.54.241
          username: u563366180
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: 65002
          script: |
            cd /home/u563366180/public_html/my-devsite
            git pull origin main